add anomality for main search engine
mozilla/docker-etl pull request #52
Opened 2022-05-21 05:42 UTC by xluo-ds

original look at over all engines, now add anomaly for Google/Bing/DDG/Yandex

Checklist for reviewer:

- [ ] Commits should reference a bug or github issue, if relevant (if a bug is
  referenced, the pull request should include the bug number in the title)
- [ ] Scan the PR and verify that no changes (particularly to
  `.circleci/config.yml`) will cause environment variables (particularly
  credentials) to be exposed in test logs
- [ ] Ensure the container image will be using permissions granted to
  [telemetry-airflow](https://github.com/mozilla/telemetry-airflow/)
  responsibly.

2022-05-21 05:43 UTC, xluo-ds commented
@akkomar  somehow I can't add Reviewers in the right side bar so tag you here. Thanks!

2022-05-23 15:08 UTC, akkomar requested changes
My only request is to make formatting consistent here (see suggested changes).

This looks good to me. I'm a bit worried that we're appending twice to the `desktop_search_alert_records` here and this job is not idempotent - I should spend some time to improve that.

2022-05-23 15:08 UTC, akkomar commented on jobs/search-alert/search_alert/main.py
> +	    3),
```suggestion
	        3 ),
```

2022-05-23 15:08 UTC, akkomar commented on jobs/search-alert/search_alert/main.py
> +	    engine,
```suggestion
	        engine,
```

2022-05-23 15:08 UTC, akkomar commented on jobs/search-alert/search_alert/main.py
> +	    engine,
```suggestion
	        engine,
```

2022-05-23 15:08 UTC, akkomar commented on jobs/search-alert/search_alert/main.py
> +	    engine,
```suggestion
	        engine,
```

2022-05-23 15:08 UTC, akkomar commented on jobs/search-alert/search_alert/main.py
> +	    value
```suggestion
	        value
```

2022-05-24 11:41 UTC, closed without merging